package si.screenme.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class EditorActivity extends androidx.activity.ComponentActivity{
    DrawView draw;File dir;ArrayList<TextView> tools=new ArrayList<>();
    @Override public void onCreate(Bundle b){super.onCreate(b);getOnBackPressedDispatcher().addCallback(this,new androidx.activity.OnBackPressedCallback(true){@Override public void handleOnBackPressed(){confirmDiscard();}});Ui.barsDark(this);dir=new File(getIntent().getStringExtra("dir"));Bitmap src=BitmapFactory.decodeFile(new File(dir,"screenshot.png").getAbsolutePath());if(src==null){Ui.toast(this,"Posnetka ni mogoče odpreti");finish();return;}build(src);}
    @Override protected void onResume(){super.onResume();OverlayService.setUiHidden(true);}
    @Override protected void onPause(){OverlayService.setUiHidden(false);super.onPause();}
    void build(Bitmap src){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(0xFF17151E);LinearLayout top=Ui.row(this);top.setPadding(Ui.dp(this,14),Ui.dp(this,8),Ui.dp(this,14),Ui.dp(this,8));TextView title=Ui.text(this,"Označi posnetek",20,Color.WHITE);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(title,Ui.weight(0,Ui.dp(this,52),1));TextView undo=mini("UNDO");undo.setOnClickListener(v->draw.undo());TextView redo=mini("REDO");redo.setOnClickListener(v->draw.redo());top.addView(undo,new LinearLayout.LayoutParams(Ui.dp(this,74),Ui.dp(this,42)));top.addView(redo,new LinearLayout.LayoutParams(Ui.dp(this,74),Ui.dp(this,42)));root.addView(top);
        HorizontalScrollView hs=new HorizontalScrollView(this);hs.setHorizontalScrollBarEnabled(false);LinearLayout toolbar=Ui.row(this);toolbar.setPadding(Ui.dp(this,12),0,Ui.dp(this,12),Ui.dp(this,8));String[] names={"✎  Svinčnik","▰  Označevalnik","○  Elipsa","□  Pravokotnik","➜  Puščica"};int[] ids={0,4,1,2,3};for(int i=0;i<names.length;i++){final int tool=ids[i];TextView x=chip(names[i]);x.setOnClickListener(v->select(tool,x));toolbar.addView(x);tools.add(x);}hs.addView(toolbar);root.addView(hs,new LinearLayout.LayoutParams(-1,Ui.dp(this,54)));
        LinearLayout controls=Ui.row(this);controls.setPadding(Ui.dp(this,14),0,Ui.dp(this,14),Ui.dp(this,8));int[] cs={0xFFFF4057,0xFFFFC928,0xFF31C48D,0xFF2F80ED,0xFF9B51E0,Color.WHITE};for(int c:cs){TextView sw=new TextView(this);sw.setBackground(Ui.shape(c,99,this));sw.setOnClickListener(v->{draw.color=c;});controls.addView(sw,new LinearLayout.LayoutParams(Ui.dp(this,34),Ui.dp(this,34)));Ui.margin(sw,0,0,8,0);}TextView thin=Ui.text(this,"Tanka",11,0xFFBBB6C6);controls.addView(thin);SeekBar width=new SeekBar(this);width.setMax(24);width.setProgress(6);width.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}public void onProgressChanged(SeekBar s,int p,boolean f){draw.stroke=Math.max(3,p);}});controls.addView(width,Ui.weight(0,Ui.dp(this,40),1));controls.addView(Ui.text(this,"Debela",11,0xFFBBB6C6));root.addView(controls);
        draw=new DrawView(this,src);root.addView(draw,new LinearLayout.LayoutParams(-1,0,1));select(0,tools.get(0));LinearLayout actions=Ui.row(this);actions.setPadding(Ui.dp(this,12),Ui.dp(this,10),Ui.dp(this,12),Ui.dp(this,14));TextView cancel=Ui.button(this,"ZAVRZI",false);cancel.setTextColor(Ui.RED);cancel.setOnClickListener(v->confirmDiscard());TextView save=Ui.button(this,"NADALJUJ",true);save.setOnClickListener(v->{Storage.bitmap(draw.flatten(),new File(dir,"annotated.png"));startActivity(new Intent(this,NoteActivity.class).putExtra("dir",dir.getAbsolutePath()).putExtra("edited",true));finish();});actions.addView(cancel,Ui.weight(0,Ui.dp(this,54),1));actions.addView(save,Ui.weight(0,Ui.dp(this,54),2));Ui.margin(save,10,0,0,0);root.addView(actions);setContentView(root);}
    TextView mini(String s){TextView v=Ui.text(this,s,11,Color.WHITE);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setBackground(Ui.shape(0xFF302B3D,12,this));return v;}
    TextView chip(String s){TextView v=Ui.text(this,s,13,0xFFE1DDEC);v.setGravity(Gravity.CENTER);v.setPadding(Ui.dp(this,14),0,Ui.dp(this,14),0);v.setBackground(Ui.shape(0xFF302B3D,14,this));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,Ui.dp(this,42));p.setMargins(0,0,Ui.dp(this,8),0);v.setLayoutParams(p);return v;}
    void select(int tool,TextView selected){draw.tool=tool;for(TextView t:tools){t.setBackground(Ui.shape(t==selected?Ui.PURPLE:0xFF302B3D,14,this));t.setTextColor(t==selected?Color.WHITE:0xFFE1DDEC);}}
    void confirmDiscard(){new AlertDialog.Builder(this).setTitle("Zavrnem spremembe?").setMessage("Posnetek bo izbrisan.").setPositiveButton("Zavrzi",(d,w)->{delete(dir);finish();}).setNegativeButton("Nadaljuj",null).show();}
    static void delete(File f){File[]a=f.listFiles();if(a!=null)for(File x:a){if(x.isDirectory())delete(x);else x.delete();}f.delete();}
    static class DrawView extends View{
        Bitmap base,layer;Canvas canvas;Paint paint=new Paint(3);Path path;float sx,sy,cx,cy,stroke=6;int tool=0,color=0xFFFF4057;ArrayList<Bitmap> undo=new ArrayList<>(),redo=new ArrayList<>();
        DrawView(Context c){this(c,Bitmap.createBitmap(1,1,Bitmap.Config.ARGB_8888));}
        DrawView(Context c,Bitmap b){super(c);base=b;layer=Bitmap.createBitmap(b.getWidth(),b.getHeight(),Bitmap.Config.ARGB_8888);canvas=new Canvas(layer);paint.setStyle(Paint.Style.STROKE);paint.setStrokeCap(Paint.Cap.ROUND);paint.setStrokeJoin(Paint.Join.ROUND);setBackgroundColor(Color.BLACK);}
        void style(){paint.setColor(color);paint.setStrokeWidth(tool==4?stroke*4:stroke);paint.setAlpha(tool==4?90:255);}
        protected void onDraw(Canvas c){super.onDraw(c);float s=scale();float ox=(getWidth()-base.getWidth()*s)/2,oy=(getHeight()-base.getHeight()*s)/2;c.save();c.translate(ox,oy);c.scale(s,s);c.drawBitmap(base,0,0,null);c.drawBitmap(layer,0,0,null);style();if(tool>=1&&tool<=3&&sx!=cx)shape(c,tool,sx,sy,cx,cy);c.restore();}
        float scale(){return Math.min(getWidth()/(float)base.getWidth(),getHeight()/(float)base.getHeight());}
        public boolean onTouchEvent(MotionEvent e){float s=scale(),ox=(getWidth()-base.getWidth()*s)/2,oy=(getHeight()-base.getHeight()*s)/2;float x=Math.max(0,Math.min(base.getWidth(),(e.getX()-ox)/s)),y=Math.max(0,Math.min(base.getHeight(),(e.getY()-oy)/s));if(e.getAction()==MotionEvent.ACTION_DOWN){saveUndo();sx=cx=x;sy=cy=y;path=new Path();path.moveTo(x,y);return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){cx=x;cy=y;if(tool==0||tool==4){path.lineTo(x,y);style();canvas.drawPath(path,paint);path=new Path();path.moveTo(x,y);}invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP){cx=x;cy=y;style();if(tool>=1&&tool<=3)shape(canvas,tool,sx,sy,cx,cy);performClick();invalidate();return true;}return true;}
        @Override public boolean performClick(){super.performClick();return true;}
        void shape(Canvas c,int t,float x1,float y1,float x2,float y2){if(t==1)c.drawOval(Math.min(x1,x2),Math.min(y1,y2),Math.max(x1,x2),Math.max(y1,y2),paint);else if(t==2)c.drawRect(Math.min(x1,x2),Math.min(y1,y2),Math.max(x1,x2),Math.max(y1,y2),paint);else{c.drawLine(x1,y1,x2,y2,paint);double a=Math.atan2(y2-y1,x2-x1),len=Math.max(24,stroke*5);c.drawLine(x2,y2,(float)(x2-len*Math.cos(a-Math.PI/6)),(float)(y2-len*Math.sin(a-Math.PI/6)),paint);c.drawLine(x2,y2,(float)(x2-len*Math.cos(a+Math.PI/6)),(float)(y2-len*Math.sin(a+Math.PI/6)),paint);}}
        void saveUndo(){undo.add(layer.copy(Bitmap.Config.ARGB_8888,true));if(undo.size()>8){Bitmap old=undo.remove(0);old.recycle();}for(Bitmap b:redo)b.recycle();redo.clear();}
        void undo(){if(undo.isEmpty())return;redo.add(layer.copy(Bitmap.Config.ARGB_8888,true));layer=undo.remove(undo.size()-1);canvas=new Canvas(layer);invalidate();}
        void redo(){if(redo.isEmpty())return;undo.add(layer.copy(Bitmap.Config.ARGB_8888,true));layer=redo.remove(redo.size()-1);canvas=new Canvas(layer);invalidate();}
        Bitmap flatten(){Bitmap out=base.copy(Bitmap.Config.ARGB_8888,true);new Canvas(out).drawBitmap(layer,0,0,null);return out;}
    }
}
