package si.screenme.app;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.projection.MediaProjectionManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
    static final int CAPTURE=42,IMPORT_IMAGES=43,CLOUD_FOLDER=44;Spinner projects;ArrayAdapter<String> projectAdapter;TextView start,status;boolean firstResume=true,fromOverlay,checkingUpdate;
    @Override public void onCreate(Bundle b){super.onCreate(b);fromOverlay=getIntent().getBooleanExtra("fromOverlay",false);Ui.bars(this);UpdateScheduler.schedule(this);SyncScheduler.schedulePeriodic(this);Storage.requeueForUpgrade(this,10);if(!getSharedPreferences("screenme",0).getBoolean("onboarded",false))startActivity(new Intent(this,OnboardingActivity.class));build();checkForUpdates();handleIncoming(getIntent());}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);fromOverlay=intent.getBooleanExtra("fromOverlay",false);handleIncoming(intent);}
    @Override protected void onResume(){super.onResume();if(fromOverlay)OverlayService.setUiHidden(true);if(!firstResume)build();firstResume=false;maybeRequestNotificationPermission();resumeAfterAutoProjectSetup();resumeCloudFolderSetup();}
    @Override protected void onPause(){if(fromOverlay&&OverlayService.running)OverlayService.setUiHidden(false);super.onPause();}
    void build(){
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(Ui.BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,20),Ui.dp(this,20),Ui.dp(this,20),Ui.dp(this,28));Ui.insets(root);scroll.addView(root);
        LinearLayout hero=Ui.card(this);hero.setBackground(Ui.shape(Ui.DARK,24,this));LinearLayout brand=Ui.row(this);ImageView logo=new ImageView(this);logo.setImageResource(R.mipmap.ic_launcher);brand.addView(logo,new LinearLayout.LayoutParams(Ui.dp(this,58),Ui.dp(this,58)));LinearLayout names=new LinearLayout(this);names.setOrientation(LinearLayout.VERTICAL);TextView name=Ui.text(this,"ScreenMe",28,Color.WHITE);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);names.addView(name);names.addView(Ui.text(this,"Capture. Mark. Fix.",13,0xFFBEB5E7));brand.addView(names,Ui.weight(0,-2,1));Ui.margin(names,12,0,0,0);status=Ui.text(this,OverlayService.running?"●  ZAJEM AKTIVEN":"●  PRIPRAVLJEN",11,OverlayService.running?0xFF6FE1AC:0xFFFFD66B);status.setTypeface(Typeface.DEFAULT,Typeface.BOLD);brand.addView(status);hero.addView(brand);TextView desc=Ui.text(this,"Najhitrejša pot od opažene napake do jasnega poročila.",16,0xFFE8E3F8);hero.addView(desc);Ui.margin(desc,0,18,0,4);root.addView(hero);addUpdateCard(root);
        TextView label=Ui.label(this,"AKTIVNI PROJEKT");root.addView(label);Ui.margin(label,2,26,0,8);LinearLayout projectCard=Ui.card(this);LinearLayout pr=Ui.row(this);projects=new Spinner(this);reloadProjects();pr.addView(projects,Ui.weight(0,Ui.dp(this,52),1));TextView plus=Ui.button(this,"+ NOV",false);plus.setOnClickListener(v->newProject());pr.addView(plus,new LinearLayout.LayoutParams(Ui.dp(this,100),Ui.dp(this,52)));Ui.margin(plus,10,0,0,0);projectCard.addView(pr);TextView manage=Ui.button(this,"UPRAVLJAJ PROJEKTE",false);manage.setOnClickListener(v->startActivity(new Intent(this,ProjectsActivity.class)));projectCard.addView(manage);Ui.margin(manage,0,12,0,0);root.addView(projectCard);
        LinearLayout stats=Ui.row(this);LinearLayout saved=stat("SHRANJENI ZAPISI",String.valueOf(records().size()));stats.addView(saved,Ui.weight(0,-2,1));boolean turbo=getSharedPreferences("screenme",0).getBoolean("turbo",false);LinearLayout sync=stat(turbo?"TURBO MODE":"SINHRONIZACIJA",syncState());sync.setClickable(true);sync.setFocusable(true);sync.setContentDescription("Odpri nadzor pošiljanja");sync.setOnClickListener(v->showSyncQueue());stats.addView(sync,Ui.weight(0,-2,1));Ui.margin(sync,10,0,0,0);root.addView(stats);Ui.margin(stats,0,14,0,0);
        start=Ui.button(this,OverlayService.running?"USTAVI ZAJEM":"ZAČNI ZAJEM",true);if(OverlayService.running)start.setBackground(Ui.ripple(this,Ui.RED,16));start.setTextSize(16);start.setCompoundDrawablesWithIntrinsicBounds(R.drawable.ic_capture,0,0,0);start.setCompoundDrawablePadding(Ui.dp(this,10));start.setOnClickListener(v->{if(OverlayService.running)stopCapture();else begin();});root.addView(start);Ui.margin(start,0,12,0,0);TextView importImages=Ui.button(this,"UVOZI SLIKE ALI POSNETKE",false);importImages.setCompoundDrawablesWithIntrinsicBounds(android.R.drawable.ic_menu_gallery,0,0,0);importImages.setCompoundDrawablePadding(Ui.dp(this,10));importImages.setOnClickListener(v->pickImages());root.addView(importImages);Ui.margin(importImages,0,8,0,20);
        LinearLayout actions=Ui.row(this);TextView library=actionButton("ZAPISI",R.drawable.ic_library);library.setOnClickListener(v->startActivity(new Intent(this,RecordsActivity.class)));actions.addView(library,Ui.weight(0,Ui.dp(this,72),1));TextView refresh=actionButton("OSVEŽI",android.R.drawable.ic_popup_sync);refresh.setOnClickListener(v->refreshAll());actions.addView(refresh,Ui.weight(0,Ui.dp(this,72),1));Ui.margin(refresh,8,0,0,0);TextView settings=actionButton("NASTAVITVE",R.drawable.ic_settings);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));actions.addView(settings,Ui.weight(0,Ui.dp(this,72),1));Ui.margin(settings,8,0,0,0);root.addView(actions);Ui.margin(actions,0,10,0,0);
        LinearLayout how=Ui.card(this);how.addView(Ui.title(this,"Kako deluje"));how.addView(step("1","En dotik","Posnetek zaslona in hitra opomba."));how.addView(step("2","Dvojni dotik","Označi s svinčnikom, oblikami ali označevalnikom."));how.addView(step("3","Kratek, nato dolg dotik","Odpri hiter uvoz slik in posnetkov."));how.addView(step("4","Pritisni in povleci","Premakni gumb ali ga spusti na X za izhod."));root.addView(how);Ui.margin(how,0,22,0,0);setContentView(scroll);
    }
    void addUpdateCard(LinearLayout root){UpdateInfo info=UpdateChecker.available(this);if(info==null)return;LinearLayout card=Ui.card(this);card.setBackground(Ui.outlined(this,0xFFFFF7DF,1));TextView title=Ui.text(this,"NOVA RAZLIČICA · "+info.versionName,13,Ui.AMBER);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);card.addView(title);TextView body=Ui.text(this,"Posodobitev ScreenMe je pripravljena za varen prenos.",15,Ui.INK);card.addView(body);Ui.margin(body,0,8,0,0);TextView download=Ui.button(this,"PRENESI POSODOBITEV",true);download.setOnClickListener(v->UpdateChecker.openDownload(this,info.apkUrl));card.addView(download);Ui.margin(download,0,14,0,0);root.addView(card);Ui.margin(card,0,14,0,0);}
    void checkForUpdates(){if(checkingUpdate)return;checkingUpdate=true;UpdateChecker.check(this,false,(info,error)->runOnUiThread(()->{checkingUpdate=false;if(!isFinishing()&&info!=null&&info.versionCode>UpdateChecker.installedVersionCode(this))build();}));}
    void refreshAll(){Storage.refreshStatus(this);SyncScheduler.scheduleNow(this);build();checkForUpdates();Ui.toast(this,"ScreenMe je osvežen");}
    void showSyncQueue(){SyncQueueDialog.show(this,this::build,()->chooseCloudFolder(false));}
    TextView actionButton(String label,int icon){TextView button=Ui.button(this,label,false);button.setCompoundDrawablesWithIntrinsicBounds(0,icon,0,0);button.setCompoundDrawablePadding(Ui.dp(this,3));button.setPadding(Ui.dp(this,3),Ui.dp(this,5),Ui.dp(this,3),Ui.dp(this,5));button.setSingleLine(true);button.setAutoSizeTextTypeUniformWithConfiguration(9,13,1,android.util.TypedValue.COMPLEX_UNIT_SP);return button;}
    void maybeRequestNotificationPermission(){if(Build.VERSION.SDK_INT<33||!getSharedPreferences("screenme",0).getBoolean("onboarded",false)||checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED)return;android.content.SharedPreferences prefs=getSharedPreferences("screenme",0);if(prefs.getBoolean("notificationPrompted",false))return;prefs.edit().putBoolean("notificationPrompted",true).apply();new AlertDialog.Builder(this).setTitle("Obvestila o posodobitvah").setMessage("Dovoli obvestila, da te ScreenMe opozori na novo različico tudi, ko aplikacija ni odprta.").setPositiveButton("Dovoli",(d,w)->requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},8)).setNegativeButton("Pozneje",null).show();}
    LinearLayout stat(String a,String b){LinearLayout c=Ui.card(this);TextView n=Ui.text(this,b,22,Ui.INK);n.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(n);c.addView(Ui.label(this,a));return c;}
    String syncState(){android.content.SharedPreferences p=getSharedPreferences("screenme",0);boolean folder=!p.getString("syncTree","").isEmpty();int pending=p.getInt(Storage.PREF_PENDING,0);boolean error=!p.getString(Storage.PREF_ERROR,"").isEmpty();String mode=SyncScheduler.state(this);if(!folder)return "Ni nastavljena";if(SyncScheduler.PAUSED.equals(mode))return "Pavza · "+pending;if(SyncScheduler.STOPPED.equals(mode))return "Ustavljeno · "+pending;if(error)return "⚠ Napaka";if(pending>0)return "Pošilja · "+pending;return p.getBoolean("turbo",false)?"⚡ Aktivna":"Aktivna";}
    LinearLayout step(String n,String title,String body){LinearLayout r=Ui.row(this);TextView badge=Ui.text(this,n,14,Color.WHITE);badge.setGravity(Gravity.CENTER);badge.setTypeface(Typeface.DEFAULT,Typeface.BOLD);badge.setBackground(Ui.shape(Ui.PURPLE,99,this));r.addView(badge,new LinearLayout.LayoutParams(Ui.dp(this,34),Ui.dp(this,34)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);TextView a=Ui.text(this,title,15,Ui.INK);a.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.addView(a);t.addView(Ui.text(this,body,13,Ui.MUTED));r.addView(t,Ui.weight(0,-2,1));Ui.margin(t,12,0,0,0);Ui.margin(r,0,16,0,0);return r;}
    ArrayList<RecordItem> records(){return RecordItem.list(getExternalFilesDir(null),null);}
    void reloadProjects(){ArrayList<String>a=ProjectStore.all(this);boolean empty=a.isEmpty();if(empty)a.add("Ni izbranega projekta");projectAdapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a);projects.setAdapter(projectAdapter);projects.setEnabled(!empty);String cur=ProjectStore.current(this);projects.setSelection(Math.max(0,a.indexOf(cur)));if(!empty)projects.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>p){}public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){ProjectStore.select(MainActivity.this,projectAdapter.getItem(pos));}});}
    void newProject(){EditText e=new EditText(this);e.setHint("Ime projekta");e.setSingleLine();e.setPadding(Ui.dp(this,16),Ui.dp(this,8),Ui.dp(this,16),Ui.dp(this,8));new AlertDialog.Builder(this).setTitle("Nov projekt").setMessage("Zapisi bodo samodejno ločeni po projektu.").setView(e).setPositiveButton("Ustvari",(d,w)->{String p=e.getText().toString().trim();if(!p.isEmpty()){ProjectStore.select(this,p);build();}}).setNegativeButton("Prekliči",null).show();}
    void pickImages(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("image/*").putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,IMPORT_IMAGES);}
    void handleIncoming(Intent intent){if(intent==null)return;if(intent.getBooleanExtra("pickImages",false)){intent.removeExtra("pickImages");new Handler(Looper.getMainLooper()).postDelayed(this::pickImages,250);return;}ArrayList<Uri> images=new ArrayList<>();if(Intent.ACTION_SEND.equals(intent.getAction())){Uri uri=intent.getParcelableExtra(Intent.EXTRA_STREAM);if(uri!=null)images.add(uri);}else if(Intent.ACTION_SEND_MULTIPLE.equals(intent.getAction())){ArrayList<Uri> shared=intent.getParcelableArrayListExtra(Intent.EXTRA_STREAM);if(shared!=null)images.addAll(shared);}if(!images.isEmpty()){intent.setAction(null);intent.removeExtra(Intent.EXTRA_STREAM);new Handler(Looper.getMainLooper()).postDelayed(()->chooseImportProject(images),250);}}
    ArrayList<Uri> selectedImages(Intent data){ArrayList<Uri> out=new ArrayList<>();if(data==null)return out;if(data.getClipData()!=null)for(int n=0;n<data.getClipData().getItemCount();n++)out.add(data.getClipData().getItemAt(n).getUri());else if(data.getData()!=null)out.add(data.getData());for(Uri uri:out)try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}return out;}
    void chooseImportProject(ArrayList<Uri> images){ArrayList<String> list=ProjectStore.all(this);if(list.isEmpty()){newImportProject(images);return;}list.add("+ Nov projekt …");String[] names=list.toArray(new String[0]);int[] selected={Math.max(0,list.indexOf(ProjectStore.current(this)))};AlertDialog dialog=new AlertDialog.Builder(this).setTitle(images.size()==1?"Izberi projekt za sliko":"Izberi projekt za "+images.size()+" slik").setSingleChoiceItems(names,selected[0],(d,which)->{selected[0]=which;if(which==names.length-1){d.dismiss();newImportProject(images);}}).setPositiveButton("Uvozi in pošlji",null).setNegativeButton("Prekliči",null).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v2->{if(selected[0]>=names.length-1)return;dialog.dismiss();importImages(images,names[selected[0]]);}));dialog.show();}
    void newImportProject(ArrayList<Uri> images){EditText input=new EditText(this);input.setSingleLine();input.setHint("Ime novega projekta");input.setPadding(Ui.dp(this,18),Ui.dp(this,8),Ui.dp(this,18),Ui.dp(this,8));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Nov projekt za slike").setView(input).setPositiveButton("Ustvari in pošlji",null).setNegativeButton("Prekliči",null).create();dialog.setOnShowListener(v->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v2->{String name=input.getText().toString().trim();if(name.isEmpty()){input.setError("Vpiši ime projekta");return;}if(ProjectStore.contains(this,name)){input.setError("Projekt s tem imenom že obstaja");return;}dialog.dismiss();importImages(images,name);}));dialog.show();}
    void importImages(ArrayList<Uri> images,String project){ProjectStore.select(this,project);AlertDialog progress=new AlertDialog.Builder(this).setTitle("Uvažam slike").setMessage("Pripravljam "+images.size()+" slik in jih dodajam v čakalno vrsto …").setCancelable(false).create();progress.show();new Thread(()->{int imported=0;String error="";for(Uri uri:images)try{ImageImporter.importOne(this,uri,project);imported++;}catch(Exception e){if(error.isEmpty())error=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}int done=imported;String failure=error;runOnUiThread(()->{if(!isFinishing())progress.dismiss();build();boolean linked=!getSharedPreferences("screenme",0).getString("syncTree","").isEmpty();String message=done+" od "+images.size()+" slik je uvoženih"+(linked?" · pošiljanje v Drive poteka":" · shranjeno lokalno");if(!failure.isEmpty())message+=" · "+failure;Ui.toast(this,message);});},"ScreenMe image import").start();}
    void projectMenu(){String p=ProjectStore.current(this);new AlertDialog.Builder(this).setTitle(p).setItems(new String[]{"Nov projekt","Odstrani projekt iz seznama"},(d,w)->{if(w==0)newProject();else new AlertDialog.Builder(this).setTitle("Odstranim projekt?").setMessage("Shranjeni posnetki ne bodo izbrisani.").setPositiveButton("Odstrani",(x,y)->{ProjectStore.remove(this,p);build();}).setNegativeButton("Prekliči",null).show();}).show();}
    void begin(){android.content.SharedPreferences prefs=getSharedPreferences("screenme",0);boolean automatic=prefs.getBoolean("autoProject",false),ready=automatic&&ForegroundAppDetector.hasAccess(this),configured=prefs.getBoolean("autoProjectConfigured",automatic);if(ready){beginCapture(true);return;}if(automatic){askForAutoProjectPermission();return;}if(!configured){askToEnableAutoProject();return;}beginCapture(false);}
    void askToEnableAutoProject(){new AlertDialog.Builder(this).setTitle("Samodejni projekti?").setMessage("ScreenMe lahko prepozna odprto aplikacijo ter sam izbere ali ustvari projekt. Če to vklopiš, imena projekta ne bo treba vpisovati.").setPositiveButton("Vklopi",(d,w)->openAutoProjectSetup()).setNegativeButton("Uporabi ročno",(d,w)->{getSharedPreferences("screenme",0).edit().putBoolean("autoProject",false).putBoolean("autoProjectConfigured",true).apply();beginCapture(false);}).setNeutralButton("Prekliči",null).show();}
    void askForAutoProjectPermission(){new AlertDialog.Builder(this).setTitle("Dokončaj samodejno zaznavanje").setMessage("Funkcija je vklopljena, vendar Androidov Dostop do uporabe še ni dovoljen. Odpri nastavitev in omogoči ScreenMe. Nato imena projekta ne bo treba vpisovati.").setPositiveButton("Odpri nastavitev",(d,w)->openAutoProjectSetup()).setNegativeButton("Preklopi na ročno",(d,w)->{getSharedPreferences("screenme",0).edit().putBoolean("autoProject",false).putBoolean("autoProjectConfigured",true).apply();beginCapture(false);}).setNeutralButton("Prekliči",null).show();}
    void openAutoProjectSetup(){getSharedPreferences("screenme",0).edit().putBoolean("autoProject",true).putBoolean("autoProjectConfigured",true).putBoolean("autoProjectStartPending",true).apply();Intent usage=new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS,Uri.parse("package:"+getPackageName()));try{startActivity(usage);}catch(Exception ignored){startActivity(new Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS));}}
    void resumeAfterAutoProjectSetup(){android.content.SharedPreferences prefs=getSharedPreferences("screenme",0);if(!prefs.getBoolean("autoProjectStartPending",false))return;prefs.edit().remove("autoProjectStartPending").apply();if(prefs.getBoolean("autoProject",false)&&ForegroundAppDetector.hasAccess(this)){new Handler(Looper.getMainLooper()).postDelayed(()->beginCapture(true),250);}else Ui.toast(this,"Samodejno zaznavanje še ni dovoljeno. Začni zajem in poskusi znova.");}
    void beginCapture(boolean automatic){String p=ProjectStore.current(this);if(!automatic&&p.isEmpty()){newProject();return;}if(!automatic)ProjectStore.select(this,p);if(getSharedPreferences("screenme",0).getString("syncTree","").isEmpty()){askForCloudFolder();return;}launchCapture();}
    void askForCloudFolder(){new AlertDialog.Builder(this).setTitle("Nastavi oblačno mapo").setMessage("Oblačna mapa še ni izbrana, zato bi novi posnetki ostali samo na telefonu. Izberi ciljno mapo ScreenMe na Google Drive ali pri drugem ponudniku.").setPositiveButton("Nastavi zdaj",(d,w)->chooseCloudFolder(true)).setNegativeButton("Samo lokalno",(d,w)->launchCapture()).setNeutralButton("Prekliči",null).show();}
    void chooseCloudFolder(boolean continueCapture){android.content.SharedPreferences prefs=getSharedPreferences("screenme",0);prefs.edit().putBoolean("cloudCapturePending",continueCapture).apply();if(!hasInternet()){new AlertDialog.Builder(this).setTitle("Poveži telefon z internetom").setMessage("Google Drive brez internetne povezave ne more prikazati map. Vključi Wi-Fi ali mobilne podatke, nato se vrni v ScreenMe.").setPositiveButton("Odpri omrežje",(d,w)->{prefs.edit().putBoolean("cloudPickerAfterSetup",true).apply();startActivity(new Intent(Settings.ACTION_WIRELESS_SETTINGS));}).setNegativeButton("Vseeno odpri",(d,w)->launchCloudFolderPicker()).setNeutralButton("Prekliči",(d,w)->prefs.edit().remove("cloudCapturePending").apply()).show();return;}if(driveNeedsOpening()){new AlertDialog.Builder(this).setTitle("Najprej odpri Google Drive").setMessage("Google Drive je arhiviran ali onemogočen do prve uporabe, zato ga izbirnik map še ne pokaže. Odpri Drive enkrat in se nato vrni v ScreenMe.").setPositiveButton("Odpri Drive",(d,w)->openDriveForSetup()).setNegativeButton("Drugi ponudnik",(d,w)->launchCloudFolderPicker()).setNeutralButton("Prekliči",(d,w)->prefs.edit().remove("cloudCapturePending").apply()).show();return;}launchCloudFolderPicker();}
    void launchCloudFolderPicker(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,CLOUD_FOLDER);}
    boolean hasInternet(){android.net.ConnectivityManager manager=(android.net.ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);if(manager==null)return false;android.net.Network network=manager.getActiveNetwork();android.net.NetworkCapabilities capabilities=network==null?null:manager.getNetworkCapabilities(network);return capabilities!=null&&capabilities.hasCapability(android.net.NetworkCapabilities.NET_CAPABILITY_INTERNET)&&capabilities.hasCapability(android.net.NetworkCapabilities.NET_CAPABILITY_VALIDATED);}
    boolean driveNeedsOpening(){try{getPackageManager().getApplicationInfo("com.google.android.apps.docs",0);int state=getPackageManager().getApplicationEnabledSetting("com.google.android.apps.docs");return state==PackageManager.COMPONENT_ENABLED_STATE_DISABLED||state==PackageManager.COMPONENT_ENABLED_STATE_DISABLED_USER||state==PackageManager.COMPONENT_ENABLED_STATE_DISABLED_UNTIL_USED;}catch(Exception ignored){return false;}}
    void openDriveForSetup(){Intent drive=getPackageManager().getLaunchIntentForPackage("com.google.android.apps.docs");if(drive==null){try{drive=new Intent(Intent.ACTION_VIEW,Uri.parse("market://details?id=com.google.android.apps.docs"));}catch(Exception ignored){drive=new Intent(Intent.ACTION_VIEW,Uri.parse("https://play.google.com/store/apps/details?id=com.google.android.apps.docs"));}}getSharedPreferences("screenme",0).edit().putBoolean("cloudPickerAfterSetup",true).apply();startActivity(drive);}
    void resumeCloudFolderSetup(){android.content.SharedPreferences prefs=getSharedPreferences("screenme",0);if(!prefs.getBoolean("cloudPickerAfterSetup",false))return;prefs.edit().remove("cloudPickerAfterSetup").apply();if(hasInternet()&&!driveNeedsOpening())new Handler(Looper.getMainLooper()).postDelayed(this::launchCloudFolderPicker,300);else Ui.toast(this,"Za Drive vključi internet in enkrat odpri aplikacijo Google Drive.");}
    void launchCapture(){if(!Settings.canDrawOverlays(this)){startActivity(new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,Uri.parse("package:"+getPackageName())));Ui.toast(this,"Dovoli prikaz čez druge aplikacije, nato znova pritisni Začni zajem.");return;}MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);startActivityForResult(m.createScreenCaptureIntent(),CAPTURE);}
    void stopCapture(){stopService(new Intent(this,OverlayService.class));OverlayService.running=false;fromOverlay=false;Ui.toast(this,"Zajem je ustavljen");build();}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==CLOUD_FOLDER){android.content.SharedPreferences prefs=getSharedPreferences("screenme",0);boolean continueCapture=prefs.getBoolean("cloudCapturePending",false);prefs.edit().remove("cloudCapturePending").apply();if(result==RESULT_OK&&data!=null&&data.getData()!=null){Uri folder=data.getData();try{getContentResolver().takePersistableUriPermission(folder,Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);prefs.edit().putString("syncTree",folder.toString()).putBoolean("syncDirect",true).remove(Storage.PREF_ERROR).apply();SyncScheduler.resume(this);int queued=Storage.queueAllRecords(this);build();Ui.toast(this,queued==0?"Oblačna mapa je nastavljena":"Mapa je nastavljena · pošiljam "+queued+" zapisov");if(continueCapture)new Handler(Looper.getMainLooper()).postDelayed(this::launchCapture,250);else new Handler(Looper.getMainLooper()).postDelayed(this::showSyncQueue,250);}catch(Exception error){Ui.toast(this,"ScreenMe ni dobil dovoljenja za pisanje v izbrano mapo");}}return;}if(req==IMPORT_IMAGES&&result==RESULT_OK){ArrayList<Uri> images=selectedImages(data);if(images.isEmpty())Ui.toast(this,"Slika ni bila izbrana");else chooseImportProject(images);return;}if(req==CAPTURE&&result==RESULT_OK&&data!=null){startForegroundService(new Intent(this,OverlayService.class).putExtra("resultCode",result).putExtra("data",data));Ui.toast(this,"ScreenMe je pripravljen");moveTaskToBack(true);}}
}
