package si.screenme.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;

public class NoteActivity extends androidx.activity.ComponentActivity{
    File dir;boolean edited;EditText title,note;Spinner severity;
    @Override public void onCreate(Bundle b){super.onCreate(b);getOnBackPressedDispatcher().addCallback(this,new androidx.activity.OnBackPressedCallback(true){@Override public void handleOnBackPressed(){confirmDiscard();}});Ui.bars(this);dir=new File(getIntent().getStringExtra("dir"));edited=getIntent().getBooleanExtra("edited",false);build();}
    @Override protected void onResume(){super.onResume();OverlayService.setUiHidden(true);}
    @Override protected void onPause(){OverlayService.setUiHidden(false);super.onPause();}
    void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(Ui.BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,20),0,Ui.dp(this,20),Ui.dp(this,24));scroll.addView(root);root.addView(Ui.nav(this,"Nova opomba"));LinearLayout preview=Ui.card(this);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);File pic=new File(dir,edited?"annotated.png":"screenshot.png");image.setImageBitmap(BitmapFactory.decodeFile(pic.getAbsolutePath()));preview.addView(image,new LinearLayout.LayoutParams(-1,Ui.dp(this,240)));root.addView(preview);LinearLayout form=Ui.card(this);form.addView(Ui.label(this,"NASLOV NAPAKE"));title=new EditText(this);title.setHint("Kratek in jasen naslov");title.setSingleLine();title.setTextSize(17);form.addView(title,new LinearLayout.LayoutParams(-1,Ui.dp(this,56)));form.addView(Ui.label(this,"RESNOST"));severity=new Spinner(this);severity.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Nizka","Običajna","Visoka","Kritična"}));severity.setSelection(1);form.addView(severity,new LinearLayout.LayoutParams(-1,Ui.dp(this,50)));form.addView(Ui.label(this,"OPIS IN KORAKI"));note=new EditText(this);note.setHint("Kaj se je zgodilo? Kaj si pričakoval? Kako napako ponovimo?");note.setGravity(Gravity.TOP);note.setMinLines(5);note.setTextSize(15);form.addView(note);root.addView(form);Ui.margin(form,0,14,0,0);LinearLayout row=Ui.row(this);TextView cancel=Ui.button(this,"ZAVRZI",false);cancel.setTextColor(Ui.RED);cancel.setOnClickListener(v->confirmDiscard());TextView save=Ui.button(this,"SHRANI ZAPIS",true);save.setOnClickListener(v->save());row.addView(cancel,Ui.weight(0,Ui.dp(this,56),1));row.addView(save,Ui.weight(0,Ui.dp(this,56),2));Ui.margin(save,10,0,0,0);root.addView(row);Ui.margin(row,0,16,0,0);setContentView(scroll);title.requestFocus();}
    void save(){String t=title.getText().toString().trim(),n=note.getText().toString().trim(),sev=severity.getSelectedItem().toString();if(t.isEmpty()){title.setError("Dodaj kratek naslov");title.requestFocus();return;}if(n.isEmpty()){note.setError("Dodaj opis napake");note.requestFocus();return;}String p=ProjectStore.current(this);String md="# "+t+"\n\n**Projekt:** "+p+"  \n**Resnost:** "+sev+"\n\n## Opis\n\n"+n+"\n";Storage.text(new File(dir,"note.md"),md);Storage.text(new File(dir,"metadata.json"),Storage.json(p,t,sev,n,edited));Storage.sync(this,dir);Ui.toast(this,"Zapis je shranjen");finish();}
    void confirmDiscard(){new AlertDialog.Builder(this).setTitle("Zavrnem posnetek?").setMessage("Ta posnetek še ni shranjen.").setPositiveButton("Zavrzi",(d,w)->{EditorActivity.delete(dir);finish();}).setNegativeButton("Nadaljuj urejanje",null).show();}
}
