package si.screenme.app;
import android.app.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;

public class OnboardingActivity extends androidx.activity.ComponentActivity{
    ViewFlipper pages;TextView next,dots;int page;
    @Override public void onCreate(Bundle b){super.onCreate(b);getOnBackPressedDispatcher().addCallback(this,new androidx.activity.OnBackPressedCallback(true){@Override public void handleOnBackPressed(){done();}});Ui.bars(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,24),Ui.dp(this,12),Ui.dp(this,24),Ui.dp(this,12));Ui.insets(root);root.setBackgroundColor(Ui.BG);TextView skip=Ui.text(this,"PRESKOČI",13,Ui.PURPLE);skip.setGravity(Gravity.END|Gravity.CENTER_VERTICAL);skip.setTypeface(Typeface.DEFAULT,Typeface.BOLD);skip.setOnClickListener(v->done());root.addView(skip,new LinearLayout.LayoutParams(-1,Ui.dp(this,48)));pages=new ViewFlipper(this);pages.addView(page(R.mipmap.ic_launcher,"Dobrodošel v ScreenMe","Zabeleži napako v trenutku, ne da bi prekinil testiranje aplikacije."));pages.addView(page(android.R.drawable.ic_menu_edit,"Pokaži, ne razlagaj","Nariši, obkroži ali označi pomemben del zaslona in dodaj jasno opombo."));pages.addView(page(android.R.drawable.ic_menu_share,"Vse na enem mestu","Loči zapise po projektih ter jih sinhroniziraj v skupno oblačno mapo."));root.addView(pages,new LinearLayout.LayoutParams(-1,0,1));dots=Ui.text(this,"●  ○  ○",18,Ui.PURPLE);dots.setGravity(Gravity.CENTER);root.addView(dots,new LinearLayout.LayoutParams(-1,Ui.dp(this,48)));next=Ui.button(this,"NAPREJ",true);next.setOnClickListener(v->advance());root.addView(next,new LinearLayout.LayoutParams(-1,Ui.dp(this,56)));setContentView(root);}
    View page(int icon,String title,String body){LinearLayout p=new LinearLayout(this);p.setGravity(Gravity.CENTER);p.setOrientation(LinearLayout.VERTICAL);ImageView i=new ImageView(this);i.setImageResource(icon);if(icon!=R.mipmap.ic_launcher)i.setColorFilter(Ui.PURPLE);p.addView(i,new LinearLayout.LayoutParams(Ui.dp(this,122),Ui.dp(this,122)));TextView t=Ui.text(this,title,30,Ui.INK);t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setGravity(Gravity.CENTER);p.addView(t);Ui.margin(t,0,30,0,0);TextView b=Ui.text(this,body,17,Ui.MUTED);b.setGravity(Gravity.CENTER);b.setLineSpacing(0,1.15f);p.addView(b);Ui.margin(b,10,16,10,0);return p;}
    void advance(){if(page==2){done();return;}page++;pages.setInAnimation(this,android.R.anim.slide_in_left);pages.setOutAnimation(this,android.R.anim.slide_out_right);pages.showNext();dots.setText(page==1?"○  ●  ○":"○  ○  ●");if(page==2)next.setText(R.string.start_using);}
    void done(){getSharedPreferences("screenme",0).edit().putBoolean("onboarded",true).apply();finish();}
}
