package si.screenme.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import android.util.*;import android.view.*;import android.widget.*;import java.io.*;import java.lang.ref.*;import java.nio.*;

public class OverlayService extends Service{
    static final String CHANNEL="screenme_capture";static volatile boolean running=false;static WeakReference<OverlayService> instance=new WeakReference<>(null);boolean uiHidden;WindowManager wm;BubbleView bubble;TextView trash;WindowManager.LayoutParams bp,tp;MediaProjection projection;ImageReader reader;VirtualDisplay display;Handler handler=new Handler(Looper.getMainLooper());DisplayMetrics metrics;volatile boolean pendingCapture;boolean pendingEdit,dragging;float downX,downY;int originX,originY;
    @Override public void onCreate(){super.onCreate();instance=new WeakReference<>(this);running=true;channel();startForeground(1,notification());wm=(WindowManager)getSystemService(WINDOW_SERVICE);addBubble();}
    @Override public int onStartCommand(Intent i,int flags,int id){if(i!=null&&"stop".equals(i.getAction())){stopSelf();return START_NOT_STICKY;}if(i!=null&&projection==null){int code=i.getIntExtra("resultCode",0);Intent data=i.getParcelableExtra("data");if(data!=null){projection=((MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE)).getMediaProjection(code,data);initCapture();}}return START_NOT_STICKY;}
    void addBubble(){int size=getSharedPreferences("screenme",0).getInt("bubbleSize",62),choice=getSharedPreferences("screenme",0).getInt("bubbleColor",0);int[] colors={0xFF6246C7,0xFF087F8C,0xFFE05A67};bubble=new BubbleView(this);bubble.setImageResource(R.drawable.ic_screenme_foreground);bubble.setPadding(dp(8),dp(8),dp(8),dp(8));android.graphics.drawable.GradientDrawable bg=Ui.shape(colors[Math.max(0,Math.min(2,choice))],99,this);bg.setStroke(dp(2),Color.WHITE);bubble.setBackground(bg);bubble.setElevation(dp(8));bubble.setContentDescription("ScreenMe zajem");bp=params(dp(size),dp(size));bp.gravity=Gravity.TOP|Gravity.START;bp.x=getSharedPreferences("screenme",0).getInt("bubbleX",dp(12));bp.y=getSharedPreferences("screenme",0).getInt("bubbleY",dp(180));wm.addView(bubble,bp);trash=new TextView(this);trash.setText("×\nIZHOD");trash.setTextColor(Color.WHITE);trash.setTextSize(14);trash.setTypeface(android.graphics.Typeface.DEFAULT,android.graphics.Typeface.BOLD);trash.setGravity(Gravity.CENTER);trash.setBackground(Ui.shape(Ui.RED,28,this));trash.setElevation(dp(10));tp=params(dp(112),dp(84));tp.gravity=Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL;tp.y=dp(28);trash.setVisibility(View.GONE);wm.addView(trash,tp);
        GestureDetector gd=new GestureDetector(this,new GestureDetector.SimpleOnGestureListener(){public boolean onDown(MotionEvent e){downX=e.getRawX();downY=e.getRawY();originX=bp.x;originY=bp.y;return true;}public boolean onSingleTapConfirmed(MotionEvent e){capture(false);return true;}public boolean onDoubleTap(MotionEvent e){capture(true);return true;}});final int touchSlop=ViewConfiguration.get(this).getScaledTouchSlop();
        bubble.setOnTouchListener((v,e)->{gd.onTouchEvent(e);if(e.getAction()==MotionEvent.ACTION_MOVE&&!dragging&&Math.hypot(e.getRawX()-downX,e.getRawY()-downY)>touchSlop){dragging=true;bubble.performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);trash.setVisibility(View.VISIBLE);wm.updateViewLayout(trash,tp);}if(dragging&&e.getAction()==MotionEvent.ACTION_MOVE){bp.x=originX+(int)(e.getRawX()-downX);bp.y=originY+(int)(e.getRawY()-downY);wm.updateViewLayout(bubble,bp);return true;}if(dragging&&(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL)){dragging=false;trash.setVisibility(View.GONE);wm.updateViewLayout(trash,tp);Point screen=new Point();wm.getDefaultDisplay().getSize(screen);if(e.getRawY()>screen.y-dp(150)&&Math.abs(e.getRawX()-screen.x/2)<dp(120)){stopSelf();return true;}bp.x=e.getRawX()<screen.x/2?dp(12):screen.x-bp.width-dp(12);bp.y=Math.max(dp(40),Math.min(bp.y,screen.y-bp.height-dp(90)));wm.updateViewLayout(bubble,bp);getSharedPreferences("screenme",0).edit().putInt("bubbleX",bp.x).putInt("bubbleY",bp.y).apply();return true;}if(e.getAction()==MotionEvent.ACTION_UP)v.performClick();return true;});}
    void capture(boolean edit){if(projection==null){Toast.makeText(this,"Ponovno zaženi ScreenMe in dovoli zajem zaslona.",Toast.LENGTH_LONG).show();return;}if(pendingCapture)return;bubble.performHapticFeedback(HapticFeedbackConstants.KEYBOARD_TAP);bubble.setVisibility(View.INVISIBLE);pendingEdit=edit;handler.postDelayed(()->pendingCapture=true,500);}
    void initCapture(){metrics=new DisplayMetrics();wm.getDefaultDisplay().getRealMetrics(metrics);reader=ImageReader.newInstance(metrics.widthPixels,metrics.heightPixels,PixelFormat.RGBA_8888,2);reader.setOnImageAvailableListener(r->{Image image=null;boolean captured=false;try{image=r.acquireLatestImage();if(image==null||!pendingCapture)return;pendingCapture=false;captured=true;Image.Plane p=image.getPlanes()[0];ByteBuffer buf=p.getBuffer();int stride=p.getPixelStride(),row=p.getRowStride(),pad=row-stride*metrics.widthPixels;Bitmap wide=Bitmap.createBitmap(metrics.widthPixels+pad/stride,metrics.heightPixels,Bitmap.Config.ARGB_8888);wide.copyPixelsFromBuffer(buf);Bitmap shot=Bitmap.createBitmap(wide,0,0,metrics.widthPixels,metrics.heightPixels);wide.recycle();File dir=Storage.newRecord(this);Storage.bitmap(shot,new File(dir,"screenshot.png"));Intent next=new Intent(this,pendingEdit?EditorActivity.class:NoteActivity.class).putExtra("dir",dir.getAbsolutePath()).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);startActivity(next);}finally{if(image!=null)image.close();if(captured)handler.postDelayed(()->{if(!uiHidden)bubble.setVisibility(View.VISIBLE);},400);}},handler);projection.registerCallback(new MediaProjection.Callback(){@Override public void onStop(){stopSelf();}},handler);display=projection.createVirtualDisplay("ScreenMe",metrics.widthPixels,metrics.heightPixels,metrics.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,handler);}
    static void setUiHidden(boolean hidden){OverlayService s=instance.get();if(s!=null)s.handler.post(()->{s.uiHidden=hidden;if(s.bubble!=null)s.bubble.setVisibility(hidden?View.INVISIBLE:View.VISIBLE);});}
    void cleanupCapture(){if(display!=null){display.release();display=null;}if(reader!=null){reader.close();reader=null;}}
    WindowManager.LayoutParams params(int w,int h){return new WindowManager.LayoutParams(w,h,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,PixelFormat.TRANSLUCENT);}
    void channel(){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel(CHANNEL,"ScreenMe zajem",NotificationManager.IMPORTANCE_LOW));}
    Notification notification(){Intent stop=new Intent(this,OverlayService.class).setAction("stop");PendingIntent p=PendingIntent.getService(this,3,stop,PendingIntent.FLAG_IMMUTABLE);PendingIntent open=PendingIntent.getActivity(this,4,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE);return new Notification.Builder(this,CHANNEL).setContentTitle("ScreenMe zajema").setContentText("En dotik za opombo · dvojni za označevanje").setSmallIcon(R.drawable.ic_screenme_mono).setContentIntent(open).setOngoing(true).addAction(new Notification.Action.Builder(null,"Ustavi",p).build()).build();}
    @Override public void onDestroy(){instance.clear();running=false;cleanupCapture();if(projection!=null)projection.stop();if(bubble!=null)wm.removeView(bubble);if(trash!=null)wm.removeView(trash);super.onDestroy();}
    @Override public android.os.IBinder onBind(Intent i){return null;}int dp(int n){return Ui.dp(this,n);}
    static class BubbleView extends ImageView{
        BubbleView(Context c){super(c);}
        @Override public boolean performClick(){super.performClick();return true;}
    }
}
