package si.screenme.app;

import android.app.*;import android.content.*;import android.graphics.*;import android.net.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.core.content.FileProvider;import java.io.*;

public class RecordDetailActivity extends Activity{
    File dir;RecordItem item;
    @Override public void onCreate(Bundle b){super.onCreate(b);Ui.bars(this);dir=new File(getIntent().getStringExtra("dir"));item=new RecordItem(dir,getIntent().getStringExtra("project"));build();}
    void build(){ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(Ui.BG);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(Ui.dp(this,20),0,Ui.dp(this,20),Ui.dp(this,28));scroll.addView(root);root.addView(Ui.nav(this,"Podrobnosti zapisa"));LinearLayout imageCard=Ui.card(this);ImageView image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setImageBitmap(BitmapFactory.decodeFile(item.image.getAbsolutePath()));imageCard.addView(image,new LinearLayout.LayoutParams(-1,-2));root.addView(imageCard);LinearLayout details=Ui.card(this);details.addView(Ui.label(this,item.project+"  ·  "+item.severity));TextView title=Ui.title(this,item.title);details.addView(title);Ui.margin(title,0,8,0,0);details.addView(Ui.text(this,item.date(),13,Ui.MUTED));TextView note=Ui.text(this,clean(item.note),15,Ui.INK);note.setTextIsSelectable(true);note.setLineSpacing(0,1.18f);details.addView(note);Ui.margin(note,0,18,0,0);root.addView(details);Ui.margin(details,0,14,0,0);LinearLayout row=Ui.row(this);TextView share=Ui.button(this,"DELI",true);share.setOnClickListener(v->share());row.addView(share,Ui.weight(0,Ui.dp(this,54),1));TextView delete=Ui.button(this,"IZBRIŠI",false);delete.setTextColor(Ui.RED);delete.setOnClickListener(v->confirmDelete());row.addView(delete,Ui.weight(0,Ui.dp(this,54),1));Ui.margin(delete,10,0,0,0);root.addView(row);Ui.margin(row,0,16,0,0);setContentView(scroll);}
    String clean(String s){return s.replaceFirst("(?s)^#\\s*[^\\r\\n]+\\R*","").trim();}
    void share(){Uri uri=FileProvider.getUriForFile(this,getPackageName()+".files",item.image);Intent i=new Intent(Intent.ACTION_SEND).setType("image/png").putExtra(Intent.EXTRA_STREAM,uri).putExtra(Intent.EXTRA_SUBJECT,"ScreenMe: "+item.title).putExtra(Intent.EXTRA_TEXT,item.title+"\n\n"+clean(item.note));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Deli poročilo"));}
    void confirmDelete(){new AlertDialog.Builder(this).setTitle("Izbrišem zapis?").setMessage("Posnetka in opombe ne bo mogoče obnoviti.").setPositiveButton("Izbriši",(d,w)->{EditorActivity.delete(dir);Ui.toast(this,"Zapis je izbrisan");finish();}).setNegativeButton("Prekliči",null).show();}
}
